=== Cross-Validation Summary ===

MAE: 8.8815,

RMSE: 13.0289,

 R²: 0.9030

Best Fold: 3


✅ Weighted Ensemble Test Results:


  MAE:  9.8038

  RMSE: 13.5145
  
  R²:   0.8893

🏆 EXCELLENT PERFORMANCE ACHIEVED!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Pre-processing

In [ ]:
import numpy as np
import pandas as pd

from IPython.display import display, HTML
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.io as pio


import seaborn as sns
from importlib import reload
import matplotlib.pyplot as plt
import matplotlib
import warnings

# Configure Jupyter Notebook
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 500)
pd.set_option('display.expand_frame_repr', False)
# pd.set_option('max_colwidth', -1)
display(HTML("<style>div.output_scroll { height: 35em; }</style>"))

reload(plt)
%matplotlib inline
%config InlineBackend.figure_format ='retina'

warnings.filterwarnings('ignore')

# configure plotly graph objects
pio.renderers.default = 'iframe'
# pio.renderers.default = 'vscode'

pio.templates["ck_template"] = go.layout.Template(
    layout_colorway = px.colors.sequential.Viridis,
#     layout_hovermode = 'closest',
#     layout_hoverdistance = -1,
    layout_autosize=False,
    layout_width=800,
    layout_height=600,
    layout_font = dict(family="Calibri Light"),
    layout_title_font = dict(family="Calibri"),
    layout_hoverlabel_font = dict(family="Calibri Light"),
#     plot_bgcolor="white",
)

# pio.templates.default = 'seaborn+ck_template+gridon'
pio.templates.default = 'ck_template+gridon'
# pio.templates.default = 'seaborn+gridon'
# pio.templates

In [ ]:
index_names = ['engine', 'cycle']
setting_names = ['setting_1', 'setting_2', 'setting_3']
sensor_names=[ "(Fan inlet temperature) (◦R)",
"(LPC outlet temperature) (◦R)",
"(HPC outlet temperature) (◦R)",
"(LPT outlet temperature) (◦R)",
"(Fan inlet Pressure) (psia)",
"(bypass-duct pressure) (psia)",
"(HPC outlet pressure) (psia)",
"(Physical fan speed) (rpm)",
"(Physical core speed) (rpm)",
"(Engine pressure ratio(P50/P2)",
"(HPC outlet Static pressure) (psia)",
"(Ratio of fuel flow to Ps30) (pps/psia)",
"(Corrected fan speed) (rpm)",
"(Corrected core speed) (rpm)",
"(Bypass Ratio) ",
"(Burner fuel-air ratio)",
"(Bleed Enthalpy)",
"(Required fan speed)",
"(Required fan conversion speed)",
"(High-pressure turbines Cool air flow)",
"(Low-pressure turbines Cool air flow)" ]
col_names = index_names + setting_names + sensor_names

In [ ]:
df_train = pd.read_csv('drive/MyDrive/archive/CMaps/train_FD003.txt',sep=r'\s+',header=None,index_col=False,names=col_names)
df_test = pd.read_csv('drive/MyDrive/archive/CMaps/test_FD003.txt',sep=r'\s+',header=None,index_col=False,names=col_names)
df_test_RUL = pd.read_csv('drive/MyDrive/archive/CMaps/RUL_FD003.txt',sep=r'\s+',header=None,index_col=False,names=['RUL'])

In [ ]:
keep_features = [
    "(Fan inlet temperature) (◦R)",
    "(LPC outlet temperature) (◦R)",
    "(HPC outlet temperature) (◦R)",
    "(LPT outlet temperature) (◦R)",
    "(Fan inlet Pressure) (psia)",
    "(bypass-duct pressure) (psia)",
    "(HPC outlet pressure) (psia)",
    "(Physical fan speed) (rpm)",
    "(Physical core speed) (rpm)",
    "(Engine pressure ratio(P50/P2)",
    "(HPC outlet Static pressure) (psia)",
    "(Ratio of fuel flow to Ps30) (pps/psia)",
    "(Corrected fan speed) (rpm)",
    "(Corrected core speed) (rpm)",
    "(Bypass Ratio) ",
    "(Burner fuel-air ratio)",
    "(Bleed Enthalpy)",
    "(Required fan speed)",
    "(Required fan conversion speed)",
    "(High-pressure turbines Cool air flow)",
    "(Low-pressure turbines Cool air flow)",
    "setting_1",
    "setting_2",
    "setting_3"
]

In [ ]:
features = list(keep_features)

In [ ]:
# define the maximum life of each engine, as this could be used to obtain the RUL at each point in time of the engine's life
df_train_RUL = df_train.groupby(['engine']).agg({'cycle':'max'})
df_train_RUL.rename(columns={'cycle':'life'},inplace=True)
df_train_RUL.head()

        life
engine
1        259
2        253
3        222
4        272
5        213

In [ ]:
df_train=df_train.merge(df_train_RUL,how='left',on=['engine'])

In [ ]:
df_train['RUL']=df_train['life']-df_train['cycle']
df_train.drop(['life'],axis=1,inplace=True)

# the RUL prediction is only useful nearer to the end of the engine's life, therefore we put an upper limit on the RUL
# this is a bit sneaky, since it supposes that the test set has RULs of less than this value, the closer you are
# to the true value, the more accurate the model will be
df_train['RUL'][df_train['RUL']>125]=125
df_train.head()

   engine  cycle  setting_1  setting_2  setting_3  (Fan inlet temperature) (◦R)  (LPC outlet temperature) (◦R)  (HPC outlet temperature) (◦R)  (LPT outlet temperature) (◦R)  (Fan inlet Pressure) (psia)  (bypass-duct pressure) (psia)  (HPC outlet pressure) (psia)  (Physical fan speed) (rpm)  (Physical core speed) (rpm)  (Engine pressure ratio(P50/P2)  (HPC outlet Static pressure) (psia)  (Ratio of fuel flow to Ps30) (pps/psia)  (Corrected fan speed) (rpm)  (Corrected core speed) (rpm)  (Bypass Ratio)   (Burner fuel-air ratio)  (Bleed Enthalpy)  (Required fan speed)  (Required fan conversion speed)  (High-pressure turbines Cool air flow)  (Low-pressure turbines Cool air flow)  RUL
0       1      1    -0.0005     0.0004      100.0                        518.67                         642.36                        1583.23                        1396.84                        14.62                          21.61                        553.97                     2387.96                      9062.17                             1.3                                47.30                                   522.31                      2388.01                       8145.32           8.4246                     0.03               391                  2388                            100.0                                   39.11                                23.3537  125
1       1      2     0.0008    -0.0003      100.0                        518.67                         642.50                        1584.69                        1396.89                        14.62                          21.61                        554.55                     2388.00                      9061.78                             1.3                                47.23                                   522.42                      2388.03                       8152.85           8.4403                     0.03               392                  2388                            100.0                                   38.99                                23.4491  125
2       1      3    -0.0014    -0.0002      100.0                        518.67                         642.18                        1582.35                        1405.61                        14.62                          21.61                        554.43                     2388.03                      9070.23                             1.3                                47.22                                   522.03                      2388.00                       8150.17           8.3901                     0.03               391                  2388                            100.0                                   38.85                                23.3669  125
3       1      4    -0.0020     0.0001      100.0                        518.67                         642.92                        1585.61                        1392.27                        14.62                          21.61                        555.21                     2388.00                      9064.57                             1.3                                47.24                                   522.49                      2388.08                       8146.56           8.3878                     0.03               392                  2388                            100.0                                   38.96                                23.2951  125
4       1      5     0.0016     0.0000      100.0                        518.67                         641.68                        1588.63                        1397.65                        14.62                          21.61                        554.74                     2388.04                      9076.14                             1.3                                47.15                                   522.58                      2388.03                       8147.80           8.3869                     0.03               392                  2388                            100.0                                   39.14                                23.4583  125

In [ ]:
def create_sequences(df, window_size, stride, engine_col='engine'):
    sequences, targets, engine_ids = [], [], []

    for engine_id in df[engine_col].unique():
        engine_data = df[df[engine_col] == engine_id].sort_values('cycle')
        feature_cols = [col for col in engine_data.columns if col not in ['engine', 'cycle', 'RUL']]

        values = engine_data[feature_cols].values
        rul_values = engine_data['RUL'].values

        for i in range(0, len(values) - window_size + 1, stride):
            sequences.append(values[i:i + window_size])
            targets.append(rul_values[i + window_size - 1])
            engine_ids.append(engine_id)

    return np.array(sequences), np.array(targets), np.array(engine_ids)



# Scale features
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
feature_cols = [col for col in df_train.columns if col not in ['engine', 'cycle', 'RUL']]
df_train[feature_cols] = scaler.fit_transform(df_train[feature_cols])
df_test[feature_cols] = scaler.transform(df_test[feature_cols])

In [ ]:
pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.19.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.19.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.10.0)
Requirement already satisfied: numpy<2.2.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.15.1)
Requirement already satisfied: ml-dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.46.3)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow) (0.18.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.19.0->tensorflow) (3.1.5)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.19.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow) (0.1.2)

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GroupKFold
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import tensorflow as tf
from tensorflow.keras import layers, models, callbacks, regularizers
from tensorflow.keras.optimizers import Adam
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
# ============================================================
# ADVANCED RUL PREDICTION: Gated Ensemble BiLSTM + Attention (Optimized)
# ============================================================

import tensorflow as tf
from tensorflow.keras import layers, models, regularizers, callbacks, optimizers
import numpy as np
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# MODIFIED create_sequences function to handle missing 'RUL' column for test set
def create_sequences(df, window_size, stride, engine_col='engine'):
    sequences, targets, engine_ids = [], [], []

    # Check if 'RUL' column exists in the DataFrame
    has_rul = 'RUL' in df.columns

    for engine_id in df[engine_col].unique():
        engine_data = df[df[engine_col] == engine_id].sort_values('cycle')
        feature_cols = [col for col in engine_data.columns if col not in ['engine', 'cycle', 'RUL']]

        values = engine_data[feature_cols].values

        if has_rul:
            rul_values = engine_data['RUL'].values
        else:
            # If RUL column is not present (e.g., for test data), create a dummy array.
            # These 'targets' will be discarded for X_test anyway.
            rul_values = np.array([])

        # Ensure there are enough data points for the window
        if len(values) < window_size:
            continue # Skip engines that are too short for a single sequence

        for i in range(0, len(values) - window_size + 1, stride):
            sequences.append(values[i:i + window_size])
            if has_rul: # Only append RUL target if RUL column exists
                targets.append(rul_values[i + window_size - 1])
            engine_ids.append(engine_id)

    return np.array(sequences), np.array(targets), np.array(engine_ids)


CONFIG = {
    'WINDOW_SIZE': 60,        # FD001 engines avg ~200 cycles; 30 is sharper
    'STRIDE': 1,
    'LSTM_UNITS': [128, 64],
    'DENSE_UNITS': 80,
    'DROPOUT_RATE': 0.2,      # Reduced — your CV→test gap suggests mild overfit
    'L2_REG': 0.0005,         # Slightly relaxed
    'BATCH_SIZE': 32,         # Smaller batch → better generalization
    'EPOCHS': 200,
    'LEARNING_RATE': 0.001,
    'PATIENCE': 20,           # Tighter early stopping
    'N_SPLITS': 5
}

print("\nOptimized Configuration:")
for k, v in CONFIG.items():
    print(f"  {k}: {v}")


X_train, y_train, train_engine_ids = create_sequences(
    df_train, CONFIG['WINDOW_SIZE'], CONFIG['STRIDE']
)
X_test, _, test_engine_ids = create_sequences(
    df_test, CONFIG['WINDOW_SIZE'], CONFIG['STRIDE']
)

print(f"Training sequences: {X_train.shape}")
print(f"Test sequences: {X_test.shape}")


# ============================================================
# Custom Layers
# ============================================================

class GatingLayer(layers.Layer):
    def __init__(self, num_branches, **kwargs):
        super(GatingLayer, self).__init__(**kwargs)
        self.num_branches = num_branches

    def build(self, input_shape):
        self.gate_weights = self.add_weight(
            shape=(input_shape[0][-1], self.num_branches),
            initializer='glorot_uniform',
            trainable=True
        )
        self.gate_bias = self.add_weight(
            shape=(self.num_branches,),
            initializer='zeros',
            trainable=True
        )

    def call(self, inputs):
        input_stats = tf.reduce_mean(inputs[0], axis=1)
        gate_scores = tf.nn.softmax(tf.matmul(input_stats, self.gate_weights) + self.gate_bias, axis=-1)
        gate_scores = tf.expand_dims(tf.expand_dims(gate_scores, 1), -1)
        stacked = tf.stack(inputs, axis=2)
        gated = stacked * gate_scores
        fused = tf.reduce_sum(gated, axis=2)
        return fused


class AttentionLayer(layers.Layer):
    """Attention mechanism to highlight critical timesteps after fusion."""
    def __init__(self, **kwargs):
        super(AttentionLayer, self).__init__(**kwargs)

    def build(self, input_shape):
        self.W = self.add_weight(shape=(input_shape[-1], input_shape[-1]),
                                 initializer="glorot_uniform", trainable=True)
        self.b = self.add_weight(shape=(input_shape[-1],),
                                 initializer="zeros", trainable=True)
        self.u = self.add_weight(shape=(input_shape[-1],),
                                 initializer="glorot_uniform", trainable=True)

    def call(self, x):
        u_t = tf.tanh(tf.tensordot(x, self.W, axes=1) + self.b)
        attn_scores = tf.nn.softmax(tf.tensordot(u_t, self.u, axes=1), axis=1)
        attn_scores = tf.expand_dims(attn_scores, -1)
        context = tf.reduce_sum(x * attn_scores, axis=1)
        return context


# ============================================================
# Optimized Gated BiLSTM + Attention Model
# ============================================================

def build_gated_attention_bilstm(input_shape, config):
    inputs = layers.Input(shape=input_shape, name='input')

    # Parallel branches: LSTM, GRU, CNN
    branch_lstm = layers.LSTM(64, return_sequences=True,
                              kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_lstm = layers.LayerNormalization()(branch_lstm)

    branch_gru = layers.GRU(64, return_sequences=True,
                            kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_gru = layers.LayerNormalization()(branch_gru)

    branch_cnn = layers.Conv1D(64, 5, padding='same', activation='relu',
                               kernel_regularizer=regularizers.l2(config['L2_REG']))(inputs)
    branch_cnn = layers.Conv1D(64, 3, padding='same', activation='relu',
                               kernel_regularizer=regularizers.l2(config['L2_REG']))(branch_cnn)
    branch_cnn = layers.LayerNormalization()(branch_cnn)

    fused = GatingLayer(num_branches=3)([branch_lstm, branch_gru, branch_cnn])
    fused = layers.Dropout(config['DROPOUT_RATE'])(fused)

    # BiLSTM layers for sequential modeling
    x = layers.Bidirectional(
        layers.LSTM(config['LSTM_UNITS'][0],
                    return_sequences=True,
                    kernel_regularizer=regularizers.l2(config['L2_REG'])),
        name='bilstm_1'
    )(fused)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    x = layers.Bidirectional(
        layers.LSTM(config['LSTM_UNITS'][1],
                    return_sequences=True,
                    kernel_regularizer=regularizers.l2(config['L2_REG'])),
        name='bilstm_2'
    )(x)
    x = layers.LayerNormalization()(x)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    # Attention layer
    context = AttentionLayer()(x)

    # Dense head
    x = layers.Dense(config['DENSE_UNITS'], activation='relu')(context)
    x = layers.Dropout(config['DROPOUT_RATE'])(x)

    outputs = layers.Dense(1, activation='linear', name='rul_output')(x)

    model = models.Model(inputs, outputs, name='Gated_Attention_BiLSTM')

    opt = optimizers.Adam(learning_rate=config['LEARNING_RATE'])
    model.compile(
        optimizer=opt,
        loss=tf.keras.losses.Huber(delta=12.0),
        metrics=['mae', 'mse']
    )
    return model


# ============================================================
# Train with Advanced Callbacks
# ============================================================

# ============================================================
# Train with Advanced Callbacks
# ============================================================

def train_model_with_cv(X_train, y_train, engine_ids, input_shape, config, n_splits=5):
    from sklearn.model_selection import GroupKFold

    gkf = GroupKFold(n_splits=n_splits)
    results, models_list = [], []

    for fold, (tr_idx, val_idx) in enumerate(gkf.split(X_train, y_train, engine_ids), 1):
        print(f"\n{'='*25} FOLD {fold}/{n_splits} {'='*25}")
        X_tr, X_val = X_train[tr_idx], X_train[val_idx]
        y_tr, y_val = y_train[tr_idx], y_train[val_idx]

        model = build_gated_attention_bilstm(input_shape, config)

        cb = [
            callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.4, patience=6, min_lr=5e-6),
            callbacks.EarlyStopping(monitor='val_loss', patience=config['PATIENCE'],
                                    restore_best_weights=True),
            callbacks.ModelCheckpoint(f"best_fold_{fold}.h5", save_best_only=True)
        ]

        history = model.fit(
            X_tr, y_tr,
            validation_data=(X_val, y_val),
            epochs=config['EPOCHS'],
            batch_size=config['BATCH_SIZE'],
            verbose=1,
            callbacks=cb
        )

        val_loss, val_mae, val_mse = model.evaluate(X_val, y_val, verbose=0)
        val_rmse = np.sqrt(val_mse)

        y_pred_val = model.predict(X_val, verbose=0).flatten()
        val_r2 = r2_score(y_val, y_pred_val)

        results.append({'fold': fold, 'mae': val_mae, 'rmse': val_rmse, 'r2': val_r2})
        models_list.append(model)

        print(f"Fold {fold} Results -> MAE: {val_mae:.4f}, RMSE: {val_rmse:.4f}, R²: {val_r2:.4f}")

    print("\n=== Cross-Validation Summary ===")
    avg_mae  = np.mean([r['mae']  for r in results])
    avg_rmse = np.mean([r['rmse'] for r in results])
    avg_r2   = np.mean([r['r2']   for r in results])
    print(f"MAE: {avg_mae:.4f}, RMSE: {avg_rmse:.4f}, R²: {avg_r2:.4f}")

    best_model_idx = np.argmax([r['r2'] for r in results])
    print(f"\nBest Fold: {best_model_idx + 1}")

    return models_list, results   # ← returns ALL models now


# ============================================================
# Execute Training
# ============================================================

input_shape = (X_train.shape[1], X_train.shape[2])
all_models, cv_results = train_model_with_cv(
    X_train, y_train, train_engine_ids, input_shape, CONFIG, CONFIG['N_SPLITS']
)

# ============================================================
# Ensemble ALL folds for test prediction
# ============================================================

# ============================================================
# Weighted Ensemble by fold R² score
# ============================================================

fold_r2_scores = np.array([r['r2'] for r in cv_results])
fold_weights = fold_r2_scores / fold_r2_scores.sum()  # normalize to sum=1

print("\nFold weights:")
for i, (r2, w) in enumerate(zip(fold_r2_scores, fold_weights), 1):
    print(f"  Fold {i}: R²={r2:.4f}, weight={w:.4f}")

all_preds = []
for m in all_models:
    preds = m.predict(X_test, verbose=0).flatten()
    preds = np.clip(preds, 0, None)
    all_preds.append(preds)

# Weighted average
y_test_pred_all = np.average(all_preds, axis=0, weights=fold_weights)

unique_engines = sorted(set(test_engine_ids))
y_true, y_pred = [], []
for eng_id in unique_engines:
    mask = test_engine_ids == eng_id
    y_pred.append(y_test_pred_all[mask][-1])
    y_true.append(df_test_RUL.iloc[int(eng_id) - 1]['RUL'])

y_true, y_pred = np.array(y_true), np.array(y_pred)
test_mae  = mean_absolute_error(y_true, y_pred)
test_rmse = np.sqrt(mean_squared_error(y_true, y_pred))
test_r2   = r2_score(y_true, y_pred)

print(f"\n✅ Weighted Ensemble Test Results:")
print(f"  MAE:  {test_mae:.4f}")
print(f"  RMSE: {test_rmse:.4f}")
print(f"  R²:   {test_r2:.4f}")

if test_r2 >= 0.88:
    print("\n🏆 EXCELLENT PERFORMANCE ACHIEVED!")

Optimized Configuration:
  WINDOW_SIZE: 60
  STRIDE: 1
  LSTM_UNITS: [128, 64]
  DENSE_UNITS: 80
  DROPOUT_RATE: 0.2
  L2_REG: 0.0005
  BATCH_SIZE: 32
  EPOCHS: 200
  LEARNING_RATE: 0.001
  PATIENCE: 20
  N_SPLITS: 5
Training sequences: (18820, 60, 24)
Test sequences: (10762, 60, 24)

========================= FOLD 1/5 =========================
Epoch 1/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 357.3655 - mae: 34.9776 - mse: 2454.6763

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 40s 37ms/step - loss: 357.0081 - mae: 34.9472 - mse: 2451.5505 - val_loss: 97.7982 - val_mae: 12.8026 - val_mse: 295.9217 - learning_rate: 0.0010
Epoch 2/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 85.1232 - mae: 11.5782 - mse: 247.3568

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 36s 35ms/step - loss: 85.1047 - mae: 11.5764 - mse: 247.2785 - val_loss: 64.8602 - val_mae: 9.7423 - val_mse: 171.2328 - learning_rate: 0.0010
Epoch 3/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 72.6650 - mae: 10.3560 - mse: 199.7106

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 72.6569 - mae: 10.3553 - mse: 199.6709 - val_loss: 61.4425 - val_mae: 8.4395 - val_mse: 169.3261 - learning_rate: 0.0010
Epoch 4/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 63.3807 - mae: 9.4501 - mse: 166.6411

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - loss: 63.3775 - mae: 9.4497 - mse: 166.6293 - val_loss: 60.6282 - val_mae: 8.4686 - val_mse: 175.3146 - learning_rate: 0.0010
Epoch 5/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 57.9998 - mae: 8.9118 - mse: 146.8391 - val_loss: 64.5048 - val_mae: 9.4618 - val_mse: 176.1947 - learning_rate: 0.0010
Epoch 6/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 23s 40ms/step - loss: 53.0152 - mae: 8.4442 - mse: 131.1328 - val_loss: 65.7432 - val_mae: 9.5041 - val_mse: 175.0021 - learning_rate: 0.0010
Epoch 7/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 49.9827 - mae: 8.1420 - mse: 120.6619

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 49.9817 - mae: 8.1419 - mse: 120.6567 - val_loss: 58.2522 - val_mae: 8.4385 - val_mse: 169.6541 - learning_rate: 0.0010
Epoch 8/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 48.0628 - mae: 7.9159 - mse: 115.2481

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 48.0573 - mae: 7.9153 - mse: 115.2311 - val_loss: 56.6558 - val_mae: 8.6200 - val_mse: 152.0714 - learning_rate: 0.0010
Epoch 9/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 43.9053 - mae: 7.4551 - mse: 102.8732

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 43.9053 - mae: 7.4552 - mse: 102.8712 - val_loss: 54.0329 - val_mae: 8.3876 - val_mse: 140.6457 - learning_rate: 0.0010
Epoch 10/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 41.2571 - mae: 7.1773 - mse: 94.6367 - val_loss: 58.2820 - val_mae: 8.5385 - val_mse: 161.4007 - learning_rate: 0.0010
Epoch 11/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - loss: 42.3017 - mae: 7.2840 - mse: 97.9303 - val_loss: 61.6125 - val_mae: 8.9778 - val_mse: 168.5171 - learning_rate: 0.0010
Epoch 12/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 41.5232 - mae: 7.1864 - mse: 95.4314 - val_loss: 57.0861 - val_mae: 8.1630 - val_mse: 151.2350 - learning_rate: 0.0010
Epoch 13/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 40.0600 - mae: 7.0094 - mse: 91.8234 - val_loss: 58.7520 - val_mae: 8.4420 - val_mse: 166.1845 - learning_rate: 0.0010
Epoch 14/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 38.3321 - mae: 6.8436 - mse: 86.5074 - val_loss: 66.3530 - val_mae: 9.2838 - val_mse: 195.6824 - learning_rate: 0.0010
Epoch 15/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 39.3724 - mae: 6.9601 - mse: 90.2876 - val_loss: 60.3833 - val_mae: 8.5891 - val_mse: 163.4894 - learning_rate: 0.0010
Epoch 16/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 35.5967 - mae: 6.4973 - mse: 79.0130 - val_loss: 60.3904 - val_mae: 8.3620 - val_mse: 165.1277 - learning_rate: 4.0000e-04
Epoch 17/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - loss: 34.5436 - mae: 6.3413 - mse: 76.0338 - val_loss: 65.1621 - val_mae: 9.2079 - val_mse: 183.2189 - learning_rate: 4.0000e-04
Epoch 18/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 34.6139 - mae: 6.3286 - mse: 77.4588 - val_loss: 62.9547 - val_mae: 9.1238 - val_mse: 170.8422 - learning_rate: 4.0000e-04
Epoch 19/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 33.8816 - mae: 6.2618 - mse: 74.5642 - val_loss: 63.8853 - val_mae: 9.1818 - val_mse: 169.7004 - learning_rate: 4.0000e-04
Epoch 20/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 34.0295 - mae: 6.2799 - mse: 75.1208 - val_loss: 72.9101 - val_mae: 9.9023 - val_mse: 212.8215 - learning_rate: 4.0000e-04
Epoch 21/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 34.1511 - mae: 6.3004 - mse: 75.8774 - val_loss: 67.4637 - val_mae: 9.1391 - val_mse: 192.5475 - learning_rate: 4.0000e-04
Epoch 22/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 32.3538 - mae: 6.0620 - mse: 71.4409 - val_loss: 68.4861 - val_mae: 9.4294 - val_mse: 195.1327 - learning_rate: 1.6000e-04
Epoch 23/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 32.0860 - mae: 6.0642 - mse: 69.9188 - val_loss: 72.4253 - val_mae: 9.7071 - val_mse: 210.3772 - learning_rate: 1.6000e-04
Epoch 24/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 31.8166 - mae: 5.9908 - mse: 69.5932 - val_loss: 68.6157 - val_mae: 9.3849 - val_mse: 193.5627 - learning_rate: 1.6000e-04
Epoch 25/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 32.6731 - mae: 6.1081 - mse: 71.3969 - val_loss: 73.2115 - val_mae: 9.7985 - val_mse: 214.2051 - learning_rate: 1.6000e-04
Epoch 26/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 22s 37ms/step - loss: 31.4187 - mae: 5.9535 - mse: 68.5415 - val_loss: 68.3624 - val_mae: 9.3763 - val_mse: 196.1292 - learning_rate: 1.6000e-04
Epoch 27/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 32.3294 - mae: 6.0586 - mse: 70.8228 - val_loss: 71.2265 - val_mae: 9.6178 - val_mse: 205.7486 - learning_rate: 1.6000e-04
Epoch 28/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 31.7471 - mae: 6.0083 - mse: 68.8342 - val_loss: 72.2057 - val_mae: 9.4770 - val_mse: 211.5678 - learning_rate: 6.4000e-05
Epoch 29/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 31.8148 - mae: 5.9817 - mse: 69.7732 - val_loss: 72.2220 - val_mae: 9.7594 - val_mse: 211.2245 - learning_rate: 6.4000e-05
Fold 1 Results -> MAE: 8.3876, RMSE: 11.8594, R²: 0.9204

========================= FOLD 2/5 =========================
Epoch 1/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 366.4359 - mae: 35.8112 - mse: 2461.2373

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 26s 37ms/step - loss: 366.0704 - mae: 35.7800 - mse: 2458.1421 - val_loss: 77.8193 - val_mae: 10.7614 - val_mse: 222.6732 - learning_rate: 0.0010
Epoch 2/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 93.7789 - mae: 12.3959 - mse: 280.0948

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 93.7566 - mae: 12.3939 - mse: 280.0002 - val_loss: 66.4922 - val_mae: 9.8399 - val_mse: 189.3663 - learning_rate: 0.0010
Epoch 3/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 76.6926 - mae: 10.7834 - mse: 210.7658 - val_loss: 76.9609 - val_mae: 10.9259 - val_mse: 225.8065 - learning_rate: 0.0010
Epoch 4/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 66.4758 - mae: 9.8281 - mse: 171.4127 - val_loss: 69.3205 - val_mae: 9.8934 - val_mse: 203.5022 - learning_rate: 0.0010
Epoch 5/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 58.3081 - mae: 9.0166 - mse: 146.7283 - val_loss: 68.2456 - val_mae: 9.8853 - val_mse: 201.5729 - learning_rate: 0.0010
Epoch 6/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 53.1541 - mae: 8.5049 - mse: 129.9252

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 53.1427 - mae: 8.5037 - mse: 129.8930 - val_loss: 63.9669 - val_mae: 9.1262 - val_mse: 187.7424 - learning_rate: 0.0010
Epoch 7/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - loss: 47.6348 - mae: 7.9092 - mse: 114.4500 - val_loss: 71.5144 - val_mae: 10.0519 - val_mse: 223.0092 - learning_rate: 0.0010
Epoch 8/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 45.6745 - mae: 7.7052 - mse: 108.5867

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 45.6681 - mae: 7.7045 - mse: 108.5648 - val_loss: 63.0241 - val_mae: 9.0788 - val_mse: 182.1670 - learning_rate: 0.0010
Epoch 9/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 41.3509 - mae: 7.2718 - mse: 94.9999 - val_loss: 63.0489 - val_mae: 9.1122 - val_mse: 182.7987 - learning_rate: 0.0010
Epoch 10/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 39.7201 - mae: 7.0465 - mse: 90.5340 - val_loss: 70.1561 - val_mae: 9.7606 - val_mse: 209.3431 - learning_rate: 0.0010
Epoch 11/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 39.8050 - mae: 7.0618 - mse: 89.6646 - val_loss: 70.3207 - val_mae: 9.4046 - val_mse: 215.6586 - learning_rate: 0.0010
Epoch 12/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 38.0033 - mae: 6.8339 - mse: 85.6966 - val_loss: 68.2437 - val_mae: 9.4834 - val_mse: 210.0140 - learning_rate: 0.0010
Epoch 13/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 35.8307 - mae: 6.5902 - mse: 79.1691 - val_loss: 70.9027 - val_mae: 9.4747 - val_mse: 226.5000 - learning_rate: 0.0010
Epoch 14/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 35.4891 - mae: 6.5622 - mse: 78.0322 - val_loss: 69.5463 - val_mae: 9.3183 - val_mse: 219.0403 - learning_rate: 0.0010
Epoch 15/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 33.1126 - mae: 6.2172 - mse: 72.9595 - val_loss: 66.9405 - val_mae: 9.0395 - val_mse: 208.3326 - learning_rate: 4.0000e-04
Epoch 16/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 32.6775 - mae: 6.1446 - mse: 71.6250 - val_loss: 69.9915 - val_mae: 9.4034 - val_mse: 221.9786 - learning_rate: 4.0000e-04
Epoch 17/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 33.0911 - mae: 6.1903 - mse: 73.0483 - val_loss: 73.5560 - val_mae: 9.8791 - val_mse: 236.0901 - learning_rate: 4.0000e-04
Epoch 18/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 31.8580 - mae: 6.0642 - mse: 69.3265 - val_loss: 65.2839 - val_mae: 8.8057 - val_mse: 202.0614 - learning_rate: 4.0000e-04
Epoch 19/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 32.6248 - mae: 6.1529 - mse: 71.2355 - val_loss: 73.6744 - val_mae: 9.5850 - val_mse: 238.1354 - learning_rate: 4.0000e-04
Epoch 20/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 31.3875 - mae: 6.0381 - mse: 67.9951 - val_loss: 78.1800 - val_mae: 10.2211 - val_mse: 256.6127 - learning_rate: 4.0000e-04
Epoch 21/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 30.5336 - mae: 5.9104 - mse: 65.8176 - val_loss: 78.5009 - val_mae: 10.3587 - val_mse: 253.7826 - learning_rate: 1.6000e-04
Epoch 22/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 30.1465 - mae: 5.8509 - mse: 65.0509 - val_loss: 72.9411 - val_mae: 9.9749 - val_mse: 228.4295 - learning_rate: 1.6000e-04
Epoch 23/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 21s 36ms/step - loss: 30.6016 - mae: 5.9007 - mse: 65.9562 - val_loss: 67.7157 - val_mae: 9.2472 - val_mse: 213.3792 - learning_rate: 1.6000e-04
Epoch 24/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 31.0378 - mae: 5.9365 - mse: 67.2720 - val_loss: 71.9259 - val_mae: 9.4826 - val_mse: 229.9045 - learning_rate: 1.6000e-04
Epoch 25/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 30.4885 - mae: 5.8566 - mse: 66.2522 - val_loss: 75.7051 - val_mae: 10.1547 - val_mse: 240.7400 - learning_rate: 1.6000e-04
Epoch 26/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 30.3029 - mae: 5.8386 - mse: 65.4258 - val_loss: 76.1663 - val_mae: 10.0010 - val_mse: 242.3039 - learning_rate: 1.6000e-04
Epoch 27/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 30.5136 - mae: 5.8651 - mse: 66.1311 - val_loss: 73.1140 - val_mae: 9.8025 - val_mse: 233.0439 - learning_rate: 6.4000e-05
Epoch 28/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - loss: 30.2911 - mae: 5.8367 - mse: 65.3519 - val_loss: 72.9269 - val_mae: 9.8277 - val_mse: 232.1278 - learning_rate: 6.4000e-05
Fold 2 Results -> MAE: 9.0788, RMSE: 13.4969, R²: 0.8968

========================= FOLD 3/5 =========================
Epoch 1/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 330.6241 - mae: 32.7500 - mse: 2164.9563

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 27s 37ms/step - loss: 330.2978 - mae: 32.7221 - mse: 2162.2180 - val_loss: 72.0009 - val_mae: 9.4445 - val_mse: 219.3062 - learning_rate: 0.0010
Epoch 2/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 81.6770 - mae: 11.2385 - mse: 234.4949

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 81.6662 - mae: 11.2375 - mse: 234.4532 - val_loss: 49.2902 - val_mae: 8.1411 - val_mse: 127.1470 - learning_rate: 0.0010
Epoch 3/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - loss: 64.8441 - mae: 9.6606 - mse: 169.6275 - val_loss: 77.0319 - val_mae: 10.1742 - val_mse: 214.2420 - learning_rate: 0.0010
Epoch 4/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 55.1581 - mae: 8.6602 - mse: 138.1248 - val_loss: 71.7232 - val_mae: 9.3101 - val_mse: 207.2837 - learning_rate: 0.0010
Epoch 5/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 48.6266 - mae: 7.9960 - mse: 117.1462 - val_loss: 66.9621 - val_mae: 9.0275 - val_mse: 192.4221 - learning_rate: 0.0010
Epoch 6/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 43.0164 - mae: 7.3995 - mse: 100.4342 - val_loss: 65.1395 - val_mae: 9.2645 - val_mse: 191.1819 - learning_rate: 0.0010
Epoch 7/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 39.1022 - mae: 6.9886 - mse: 88.1560 - val_loss: 69.0693 - val_mae: 9.6343 - val_mse: 194.2929 - learning_rate: 0.0010
Epoch 8/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 37.7661 - mae: 6.8577 - mse: 83.8372 - val_loss: 73.8243 - val_mae: 9.5484 - val_mse: 212.8984 - learning_rate: 0.0010
Epoch 9/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 33.0325 - mae: 6.2913 - mse: 71.5969 - val_loss: 62.1858 - val_mae: 8.4911 - val_mse: 177.4278 - learning_rate: 4.0000e-04
Epoch 10/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 30.5337 - mae: 5.9577 - mse: 65.6340 - val_loss: 64.9262 - val_mae: 8.7176 - val_mse: 181.8095 - learning_rate: 4.0000e-04
Epoch 11/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 31.1389 - mae: 6.0419 - mse: 67.0824 - val_loss: 63.8338 - val_mae: 8.7727 - val_mse: 178.0769 - learning_rate: 4.0000e-04
Epoch 12/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 20s 34ms/step - loss: 29.9998 - mae: 5.9172 - mse: 63.7626 - val_loss: 65.4114 - val_mae: 8.8836 - val_mse: 182.8218 - learning_rate: 4.0000e-04
Epoch 13/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - loss: 29.4562 - mae: 5.8500 - mse: 62.9224 - val_loss: 61.6654 - val_mae: 8.7993 - val_mse: 169.2481 - learning_rate: 4.0000e-04
Epoch 14/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 29.1397 - mae: 5.7820 - mse: 62.0956 - val_loss: 70.4287 - val_mae: 9.6080 - val_mse: 199.5507 - learning_rate: 4.0000e-04
Epoch 15/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - loss: 28.3547 - mae: 5.7079 - mse: 59.8959 - val_loss: 63.5316 - val_mae: 8.5216 - val_mse: 177.1120 - learning_rate: 1.6000e-04
Epoch 16/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 29.1005 - mae: 5.7428 - mse: 61.9820 - val_loss: 68.6810 - val_mae: 9.4286 - val_mse: 198.7965 - learning_rate: 1.6000e-04
Epoch 17/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 27.6004 - mae: 5.5597 - mse: 58.9425 - val_loss: 66.6623 - val_mae: 8.7156 - val_mse: 190.1808 - learning_rate: 1.6000e-04
Epoch 18/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 27.3085 - mae: 5.5337 - mse: 57.5069 - val_loss: 64.0416 - val_mae: 8.6560 - val_mse: 177.7128 - learning_rate: 1.6000e-04
Epoch 19/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 27.6951 - mae: 5.5819 - mse: 58.4140 - val_loss: 67.1418 - val_mae: 9.0767 - val_mse: 194.8041 - learning_rate: 1.6000e-04
Epoch 20/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 27.0492 - mae: 5.5058 - mse: 57.2392 - val_loss: 63.4788 - val_mae: 8.6819 - val_mse: 176.8997 - learning_rate: 1.6000e-04
Epoch 21/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 27.3758 - mae: 5.5334 - mse: 57.9876 - val_loss: 67.5503 - val_mae: 9.0054 - val_mse: 190.4157 - learning_rate: 6.4000e-05
Epoch 22/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - loss: 26.4780 - mae: 5.4241 - mse: 55.6901 - val_loss: 67.6702 - val_mae: 9.0988 - val_mse: 194.8796 - learning_rate: 6.4000e-05
Fold 3 Results -> MAE: 8.1411, RMSE: 11.2759, R²: 0.9280

========================= FOLD 4/5 =========================
Epoch 1/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 326.9473 - mae: 32.3760 - mse: 2170.1641

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 26s 38ms/step - loss: 326.6153 - mae: 32.3476 - mse: 2167.3735 - val_loss: 79.7996 - val_mae: 11.3462 - val_mse: 223.7011 - learning_rate: 0.0010
Epoch 2/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 78.3260 - mae: 10.9179 - mse: 219.5394

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 78.3078 - mae: 10.9163 - mse: 219.4667 - val_loss: 79.3698 - val_mae: 11.0147 - val_mse: 238.2607 - learning_rate: 0.0010
Epoch 3/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 61.8627 - mae: 9.3712 - mse: 158.5990

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - loss: 61.8605 - mae: 9.3710 - mse: 158.5904 - val_loss: 75.8578 - val_mae: 10.5596 - val_mse: 218.2089 - learning_rate: 0.0010
Epoch 4/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 55.8170 - mae: 8.6930 - mse: 139.7225

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 55.8136 - mae: 8.6928 - mse: 139.7064 - val_loss: 71.5159 - val_mae: 9.8155 - val_mse: 205.1047 - learning_rate: 0.0010
Epoch 5/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 50.5199 - mae: 8.2044 - mse: 121.7424 - val_loss: 84.9492 - val_mae: 11.3399 - val_mse: 264.6909 - learning_rate: 0.0010
Epoch 6/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 44.3915 - mae: 7.5636 - mse: 101.9726 - val_loss: 80.7152 - val_mae: 10.9409 - val_mse: 236.8458 - learning_rate: 0.0010
Epoch 7/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 42.0114 - mae: 7.2918 - mse: 96.4737 - val_loss: 88.5004 - val_mae: 11.6055 - val_mse: 267.7611 - learning_rate: 0.0010
Epoch 8/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 21s 34ms/step - loss: 39.2187 - mae: 7.0049 - mse: 87.6309 - val_loss: 81.8491 - val_mae: 10.7236 - val_mse: 244.6896 - learning_rate: 0.0010
Epoch 9/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 38.7389 - mae: 6.9365 - mse: 86.5774 - val_loss: 83.0557 - val_mae: 10.6010 - val_mse: 257.3998 - learning_rate: 0.0010
Epoch 10/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 36.5632 - mae: 6.7558 - mse: 79.9942 - val_loss: 77.9973 - val_mae: 10.4400 - val_mse: 224.8272 - learning_rate: 0.0010
Epoch 11/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 32.1871 - mae: 6.1772 - mse: 69.6208 - val_loss: 84.2353 - val_mae: 10.9964 - val_mse: 253.0240 - learning_rate: 4.0000e-04
Epoch 12/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 31.0554 - mae: 6.0535 - mse: 66.7727 - val_loss: 84.3468 - val_mae: 11.0756 - val_mse: 246.3815 - learning_rate: 4.0000e-04
Epoch 13/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 29.8353 - mae: 5.8757 - mse: 63.7830 - val_loss: 78.8140 - val_mae: 10.3240 - val_mse: 228.7726 - learning_rate: 4.0000e-04
Epoch 14/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 30.6645 - mae: 6.0051 - mse: 65.4153 - val_loss: 81.4332 - val_mae: 10.8375 - val_mse: 237.1580 - learning_rate: 4.0000e-04
Epoch 15/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 30.0546 - mae: 5.9405 - mse: 64.1742 - val_loss: 83.4118 - val_mae: 10.8251 - val_mse: 244.7230 - learning_rate: 4.0000e-04
Epoch 16/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 30.1823 - mae: 5.9396 - mse: 64.3124 - val_loss: 84.8311 - val_mae: 11.1444 - val_mse: 245.2178 - learning_rate: 4.0000e-04
Epoch 17/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 28.8071 - mae: 5.7380 - mse: 61.4519 - val_loss: 84.8150 - val_mae: 11.0356 - val_mse: 253.2897 - learning_rate: 1.6000e-04
Epoch 18/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 18s 37ms/step - loss: 28.4376 - mae: 5.6661 - mse: 60.7025 - val_loss: 85.2334 - val_mae: 10.9286 - val_mse: 253.3090 - learning_rate: 1.6000e-04
Epoch 19/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 27.8622 - mae: 5.6167 - mse: 59.1163 - val_loss: 90.0017 - val_mae: 11.6187 - val_mse: 270.6103 - learning_rate: 1.6000e-04
Epoch 20/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 28.6393 - mae: 5.7059 - mse: 61.1621 - val_loss: 88.1636 - val_mae: 11.3654 - val_mse: 263.6440 - learning_rate: 1.6000e-04
Epoch 21/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 27.9225 - mae: 5.6567 - mse: 59.0943 - val_loss: 86.3694 - val_mae: 11.2421 - val_mse: 249.7894 - learning_rate: 1.6000e-04
Epoch 22/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 29.4410 - mae: 5.7762 - mse: 63.5839 - val_loss: 86.0992 - val_mae: 10.9909 - val_mse: 255.3553 - learning_rate: 1.6000e-04
Epoch 23/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 27.9997 - mae: 5.6375 - mse: 59.8534 - val_loss: 84.0138 - val_mae: 10.9370 - val_mse: 247.5926 - learning_rate: 6.4000e-05
Epoch 24/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 37ms/step - loss: 28.4563 - mae: 5.6565 - mse: 60.4825 - val_loss: 84.9121 - val_mae: 11.0374 - val_mse: 248.1604 - learning_rate: 6.4000e-05
Fold 4 Results -> MAE: 9.8155, RMSE: 14.3215, R²: 0.8840

========================= FOLD 5/5 =========================
Epoch 1/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 346.2310 - mae: 34.0136 - mse: 2354.6560

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 27s 37ms/step - loss: 345.5058 - mae: 33.9515 - mse: 2348.5237 - val_loss: 71.1088 - val_mae: 10.0457 - val_mse: 197.5639 - learning_rate: 0.0010
Epoch 2/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 74.7703 - mae: 10.6000 - mse: 200.3870 - val_loss: 79.5195 - val_mae: 11.1488 - val_mse: 234.2884 - learning_rate: 0.0010
Epoch 3/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 61.7394 - mae: 9.3946 - mse: 154.8344

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 61.7252 - mae: 9.3931 - mse: 154.7938 - val_loss: 70.2629 - val_mae: 9.5899 - val_mse: 201.2285 - learning_rate: 0.0010
Epoch 4/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 49.4253 - mae: 8.1006 - mse: 117.5633 - val_loss: 76.0935 - val_mae: 10.1638 - val_mse: 237.6235 - learning_rate: 0.0010
Epoch 5/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 18s 38ms/step - loss: 43.2743 - mae: 7.4929 - mse: 99.2409 - val_loss: 74.2974 - val_mae: 10.0545 - val_mse: 220.7538 - learning_rate: 0.0010
Epoch 6/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 40.9998 - mae: 7.2011 - mse: 92.9171 - val_loss: 76.8037 - val_mae: 10.0226 - val_mse: 230.0850 - learning_rate: 0.0010
Epoch 7/200
470/471 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 38.2245 - mae: 6.9610 - mse: 84.3652

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 38.2260 - mae: 6.9611 - mse: 84.3709 - val_loss: 68.8359 - val_mae: 8.9847 - val_mse: 201.3752 - learning_rate: 0.0010
Epoch 8/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 37.7357 - mae: 6.8560 - mse: 83.7063 - val_loss: 83.3661 - val_mae: 10.5457 - val_mse: 256.0340 - learning_rate: 0.0010
Epoch 9/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 21s 35ms/step - loss: 35.5693 - mae: 6.5674 - mse: 78.5836 - val_loss: 82.7513 - val_mae: 10.4297 - val_mse: 259.6301 - learning_rate: 0.0010
Epoch 10/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 35.0724 - mae: 6.5808 - mse: 76.6374 - val_loss: 86.1914 - val_mae: 10.8023 - val_mse: 273.4341 - learning_rate: 0.0010
Epoch 11/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 22s 38ms/step - loss: 34.9686 - mae: 6.5387 - mse: 76.2339 - val_loss: 72.9887 - val_mae: 9.5229 - val_mse: 216.2301 - learning_rate: 0.0010
Epoch 12/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 34.5596 - mae: 6.5164 - mse: 74.9286 - val_loss: 76.4602 - val_mae: 9.7190 - val_mse: 230.0369 - learning_rate: 0.0010
Epoch 13/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 33.3156 - mae: 6.3054 - mse: 72.3904 - val_loss: 86.2175 - val_mae: 10.7210 - val_mse: 269.3184 - learning_rate: 0.0010
Epoch 14/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 29.9024 - mae: 5.8956 - mse: 63.8599 - val_loss: 77.6477 - val_mae: 10.0267 - val_mse: 233.3275 - learning_rate: 4.0000e-04
Epoch 15/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 35ms/step - loss: 29.8470 - mae: 5.8580 - mse: 63.5331 - val_loss: 85.3515 - val_mae: 10.6020 - val_mse: 272.6819 - learning_rate: 4.0000e-04
Epoch 16/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 30.2527 - mae: 5.8972 - mse: 64.9386 - val_loss: 90.7033 - val_mae: 11.4527 - val_mse: 295.3299 - learning_rate: 4.0000e-04
Epoch 17/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 20s 35ms/step - loss: 29.7787 - mae: 5.8519 - mse: 63.9954 - val_loss: 84.8344 - val_mae: 10.4478 - val_mse: 272.1670 - learning_rate: 4.0000e-04
Epoch 18/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 29.3761 - mae: 5.8277 - mse: 62.8254 - val_loss: 87.4472 - val_mae: 10.9621 - val_mse: 283.7622 - learning_rate: 4.0000e-04
Epoch 19/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 28.5592 - mae: 5.7164 - mse: 61.0977 - val_loss: 94.7773 - val_mae: 11.7323 - val_mse: 306.9639 - learning_rate: 4.0000e-04
Epoch 20/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 28.3300 - mae: 5.6476 - mse: 60.5823 - val_loss: 86.0383 - val_mae: 10.5225 - val_mse: 269.9930 - learning_rate: 1.6000e-04
Epoch 21/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 28.3782 - mae: 5.6438 - mse: 60.6056 - val_loss: 87.2760 - val_mae: 10.8992 - val_mse: 277.2888 - learning_rate: 1.6000e-04
Epoch 22/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 28.3815 - mae: 5.6320 - mse: 60.6760 - val_loss: 88.1161 - val_mae: 11.0400 - val_mse: 279.8030 - learning_rate: 1.6000e-04
Epoch 23/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 28.2470 - mae: 5.6290 - mse: 60.3629 - val_loss: 92.8398 - val_mae: 11.4115 - val_mse: 311.3497 - learning_rate: 1.6000e-04
Epoch 24/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 27.7693 - mae: 5.5539 - mse: 59.0493 - val_loss: 89.7654 - val_mae: 11.1940 - val_mse: 290.8286 - learning_rate: 1.6000e-04
Epoch 25/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 16s 34ms/step - loss: 27.7261 - mae: 5.5619 - mse: 59.1168 - val_loss: 92.3363 - val_mae: 11.2671 - val_mse: 314.8321 - learning_rate: 1.6000e-04
Epoch 26/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 36ms/step - loss: 26.8898 - mae: 5.4902 - mse: 56.8920 - val_loss: 92.0565 - val_mae: 11.2924 - val_mse: 306.3152 - learning_rate: 6.4000e-05
Epoch 27/200
471/471 ━━━━━━━━━━━━━━━━━━━━ 17s 35ms/step - loss: 27.3734 - mae: 5.5331 - mse: 58.2152 - val_loss: 92.2586 - val_mae: 11.3005 - val_mse: 308.0078 - learning_rate: 6.4000e-05
Fold 5 Results -> MAE: 8.9847, RMSE: 14.1907, R²: 0.8859

=== Cross-Validation Summary ===
MAE: 8.8815, RMSE: 13.0289, R²: 0.9030

Best Fold: 3

Fold weights:
  Fold 1: R²=0.9204, weight=0.2039
  Fold 2: R²=0.8968, weight=0.1986
  Fold 3: R²=0.9280, weight=0.2055
  Fold 4: R²=0.8840, weight=0.1958
  Fold 5: R²=0.8859, weight=0.1962

✅ Weighted Ensemble Test Results:
  MAE:  9.8038
  RMSE: 13.5145
  R²:   0.8893

🏆 EXCELLENT PERFORMANCE ACHIEVED!

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# ============================================================
# Prep: define y_pred_final and supporting variables
# ============================================================

y_pred_final = y_pred  # weighted ensemble predictions (from evaluation step)
final_r2     = test_r2
sorted_idx   = np.argsort(y_true)

# Single best model predictions (for comparison plot)
best_fold_idx   = np.argmax(fold_r2_scores)
y_pred_single   = np.clip(all_models[best_fold_idx].predict(X_test, verbose=0).flatten(), 0, None)

# Per-engine last-window for single model
y_pred_single_eng = []
for eng_id in unique_engines:
    mask = test_engine_ids == eng_id
    y_pred_single_eng.append(y_pred_single[mask][-1])
y_pred_single_eng = np.array(y_pred_single_eng)

y_pred_ens = y_pred_final  # alias for clarity in plot 5

# ============================================================
# Plot 1 — True vs Predicted sorted by True RUL
# ============================================================

plt.figure(figsize=(14, 4))
plt.plot(y_true[sorted_idx],       label='True RUL',
         marker='o', ms=3, color='steelblue')
plt.plot(y_pred_final[sorted_idx], label='Predicted RUL',
         marker='x', ms=3, color='tomato')
plt.xlabel('Engine (sorted by True RUL)')
plt.ylabel('RUL')
plt.title('FD003 — True vs Predicted RUL (Weighted Ensemble, sorted by True RUL)')
plt.legend()
plt.tight_layout()
plt.show()

# ============================================================
# Plot 2 — Scatter: Predicted vs True
# ============================================================

plt.figure(figsize=(6, 6))
plt.scatter(y_true, y_pred_final, alpha=0.5, s=15, color='steelblue')
mn = min(y_true.min(), y_pred_final.min())
mx = max(y_true.max(), y_pred_final.max())
plt.plot([mn, mx], [mn, mx], 'r--', label='Perfect prediction')
plt.xlabel('True RUL')
plt.ylabel('Predicted RUL')
plt.title(f'FD003 — Predicted vs True RUL  (R²={final_r2:.3f})')
plt.legend()
plt.tight_layout()
plt.show()

# ============================================================
# Plot 3 — Residual Distribution
# ============================================================

residuals = y_pred_final - y_true
plt.figure(figsize=(8, 4))
plt.hist(residuals, bins=30, color='steelblue', edgecolor='white')
plt.axvline(0, color='red', linestyle='--', label='Zero bias')
plt.axvline(residuals.mean(), color='orange', linestyle='--',
            label=f'Mean bias: {residuals.mean():+.2f}')
plt.xlabel('Prediction Error (pred − true)')
plt.ylabel('Count')
plt.title('FD003 — Residual Distribution')
plt.legend()
plt.tight_layout()
plt.show()

# ============================================================
# Plot 4 — CV Fold Performance
# ============================================================

fold_labels = [f"Fold {r['fold']}" for r in cv_results]
fold_maes   = [r['mae'] for r in cv_results]
fold_r2s    = [r['r2']  for r in cv_results]

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
axes[0].bar(fold_labels, fold_maes, color='steelblue')
axes[0].set_title('FD001 — Validation MAE per Fold')
axes[0].set_ylabel('MAE')

axes[1].bar(fold_labels, fold_r2s, color='tomato')
axes[1].set_title('FD003 — Validation R² per Fold')
axes[1].set_ylabel('R²')
axes[1].axhline(0.80, color='green', linestyle='--', label='Target R²=0.80')
axes[1].legend()
plt.tight_layout()
plt.show()

# ============================================================
# Plot 5 — Single Best Fold vs Weighted Ensemble vs True RUL
# ============================================================

plt.figure(figsize=(14, 4))
plt.plot(y_true[sorted_idx],                  label='True RUL',
         color='steelblue', lw=1.5)
plt.plot(y_pred_single_eng[sorted_idx],        label=f'Best Fold (Fold {best_fold_idx+1})',
         color='orange', lw=1, alpha=0.7)
plt.plot(y_pred_ens[sorted_idx],               label='Weighted Ensemble',
         color='tomato', lw=1.5)
plt.xlabel('Engine (sorted by True RUL)')
plt.ylabel('RUL')
plt.title('FD003 — Best Single Fold vs Weighted Ensemble vs True RUL')
plt.legend()
plt.tight_layout()
plt.show()

# ============================================================
# Plot 6 — Fold Weights (FD002 specific — shows ensemble contribution)
# ============================================================

plt.figure(figsize=(8, 4))
bars = plt.bar(fold_labels, fold_weights, color='mediumpurple', edgecolor='white')
plt.axhline(1 / len(fold_weights), color='gray', linestyle='--',
            label=f'Uniform weight = {1/len(fold_weights):.3f}')
for bar, w in zip(bars, fold_weights):
    plt.text(bar.get_x() + bar.get_width() / 2,
             bar.get_height() + 0.002,
             f'{w:.3f}', ha='center', va='bottom', fontsize=9)
plt.xlabel('Fold')
plt.ylabel('Weight')
plt.title('FD003 — Ensemble Fold Weights (R²-normalized)')
plt.legend()
plt.tight_layout()
plt.show()